<!DOCTYPE html>
<html lang="en" dir="ltr"><head>
  
                           
     


<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="generator" content="Hugo 0.102.1" />
<title>Machine Learning - Final Project | Dina Arch</title>


<meta property="twitter:site" content="@dnajiarch">
<meta property="twitter:creator" content="@dnajiarch">







  
    
  
<meta name="description" content="Completion of a final project for PSTAT 231 at UC Santa Barbara.">


<meta property="og:site_name" content="Dina Arch">
<meta property="og:title" content="Machine Learning - Final Project | Dina Arch">
<meta property="og:description" content="Completion of a final project for PSTAT 231 at UC Santa Barbara." />
<meta property="og:type" content="page" />
<meta property="og:url" content="https://www.dina-arch.com/collection/machine-learning-final-project/" />
<meta property="og:locale" content="en">




    
        <meta property="og:image" content="https://www.dina-arch.com/collection/machine-learning-final-project/featured.jpg" >
        <meta property="twitter:card" content="summary_large_image">
        <meta name="twitter:image" content="https://www.dina-arch.com/collection/machine-learning-final-project/featured.jpg" >
    
    
  <meta itemprop="name" content="Machine Learning - Final Project">
<meta itemprop="description" content="BackgroundThe U.S. presidential election in 2012 did not come as a surprise. Some correctly predicted the outcome of the election correctly including Nate Silver,and many speculated about his approach.
Despite the success in 2012, the 2016 presidential election came as abig surpriseto many, and it underscored that predicting voter behavior is complicated for many reasons despite the tremendous effort in collecting, analyzing, and understanding many available datasets."><meta itemprop="datePublished" content="2021-03-15T00:00:00+00:00" />
<meta itemprop="dateModified" content="2021-12-14T16:07:42-08:00" />
<meta itemprop="wordCount" content="7706"><meta itemprop="image" content="https://www.dina-arch.com/collection/machine-learning-final-project/featured.jpg">
<meta itemprop="keywords" content="r markdown,machine learning,visualization,classification,principal components," />
  
  
  <!--[if IE]><script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
  <link rel="shortcut icon" href="/img/cat.ico" type="image/x-icon">
  <link rel="icon" href="/img/cat.ico" type="image/x-icon">
  
  
  <link rel="stylesheet" href="/style.main.min.51ef9a26ed5e31959c31ea456a050c05fbf3938c97c284a4438715138fcb2e8d.css" integrity="sha256-Ue&#43;aJu1eMZWcMepFagUMBfvzk4yXwoSkQ4cVE4/LLo0=" media="screen">
  
  
  <script src="/panelset.min.ed1ac24b6e16f4e2481e3d1d098ae66f5bc77438aef619e6e266d8ac5b00dc72.js" type="text/javascript"></script>
  
  
  <script src="/main.min.5550fcfd017088ccae55298dd74a3b7d7bfe6cc577b648c443d001196a798ca6.js" type="text/javascript"></script>
</head>
<body>
      <div class="grid-container single-series">
<header class="site-header pt4 pb2 mb4 bb b--transparent ph5 headroom z-max" role="banner">
  <nav class="site-nav db dt-l w-100" role="navigation">
    <a class="site-brand db dtc-l v-mid link no-underline w-100 w-33-l tc tl-l" href="https://www.dina-arch.com" title="Home">
      <img src="/img/cat.ico" class="dib db-l h2 w-auto" alt="Dina Arch">
    </a>
    <div class="site-links db dtc-l v-mid w-100 w-47-l tc tr-l mt3 mt0-l ttu tracked">
      
        
        
        
      <a class="link f6 f5-l dib pv1 ph2 " href="/" title="Home">Home</a>
      
        
        
        
      <a class="link f6 f5-l dib pv1 ph2 active" href="/collection/" title="Project Portfolio">R Projects</a>
      
        
        
        
      <a class="link f6 f5-l dib pv1 ph2 " href="https://ucsb.box.com/s/ihm263kmu5wm2ko9ar0eju849qdqwb73" title="CV">CV</a>
      
      
    </div>
  </nav>
</header>


<main class="page-main ph4 pt4" role="main">
  <section class="page-content mw7 center">
    <article class="post-content pa0 pr3-l">
      <header class="post-header">
        <h4 class="breadcrumb pb5">

  
    
      
  
    
      
  

    
    
      <a href="/collection/">R Projects</a>
    
  

    
    
      Machine Learning - Final Project
    
  

</h4>




        
        <h1 class="f1 lh-solid measure-narrow mb3 fw4">Machine Learning - Final Project</h1>
        <h4 class="f4 mt0 mb4 lh-title measure">Completion of a final project for PSTAT 231 at UC Santa Barbara.</h4>
        
        
        
        
      
        
      </header>
      <section class="post-body pt5 pb4">
        


<div id="background" class="section level1">
<h1>Background</h1>
<p>The U.S. presidential election in 2012 did not come as a surprise. Some correctly predicted the outcome of the election correctly including <a href="https://en.wikipedia.org/wiki/Nate_Silver">Nate Silver</a>,
and <a href="https://www.theguardian.com/science/grrlscientist/2012/nov/08/nate-sliver-predict-us-election">many speculated about his approach</a>.</p>
<p>Despite the success in 2012, the 2016 presidential election came as a
<a href="https://fivethirtyeight.com/features/the-polls-missed-trump-we-asked-pollsters-why/">big surprise</a>
to many, and it underscored that predicting voter behavior is complicated for many reasons despite the tremendous effort in collecting, analyzing, and understanding many available datasets.</p>
<p>Your final project will be to merge census data with 2016 voting data to analyze the election outcome.</p>
<p>To familiarize yourself with the general problem of predicting election outcomes, read the articles linked above and answer the following questions. Limit your responses to one paragraph for each.</p>
<ol style="list-style-type: decimal">
<li>What makes voter behavior prediction (and thus election forecasting) a hard problem?</li>
</ol>
<p><strong>In general, predicting behavior has its limitations. As mentioned in the fivethirtyeight.com article, there is always going to be statistical noise and nonresponse bias to pre-election polls which is then not representative of voter turnout. For the 2016 election specifically, there may have been people who had a preference for a certain candidate during pre-election polls and perhaps changed their mind at the voting booth.</strong></p>
<ol start="2" style="list-style-type: decimal">
<li>What was unique to Nate Silver’s approach in 2012 that allowed him to achieve good predictions?</li>
</ol>
<p><strong>The Guardian mentions modeling voting behavior and polls, the mathematical model being: Proportion of people saying they will vote for Obama is that actual percentage + the house effect + sampling variation. Based on Wikipedia’s discussion, he published an interactive webpage that allowed readers to predictor the outcome of the election based on three variables: President Obama’s favorability ratings, the rate of GDP growth, and how conservative the Republication opponent would be. It’s doesn’t mention if he used the responses in his model, however.</strong></p>
<ol start="3" style="list-style-type: decimal">
<li>What went wrong in 2016? What do you think should be done to make future predictions better?</li>
</ol>
<p><strong>As mentioned before there was high error, such as statistical noise and nonresponse bias. There could be many reasons for this, one example the article mentioned was that pollsters could have been embarrassed to admit who they were supporting. They also could have had a changed their mind about a candidate between the pre-election polls and when voting.</strong></p>
</div>
<div id="data" class="section level1">
<h1>Data</h1>
<p>The <code>project_data.RData</code> binary file contains three datasets: tract-level 2010 census data, stored as <code>census</code>; metadata <code>census_meta</code> with variable descriptions and types; and county-level vote tallies from the 2016 election, stored as <code>election_raw</code>.</p>
<pre class="r"><code>load(&#39;project_data.RData&#39;)</code></pre>
<div id="election-data" class="section level2">
<h2>Election data</h2>
<p>Some example rows of the election data are shown below:</p>
<pre class="r"><code>filter(election_raw, !is.na(county)) %&gt;% 
  head()</code></pre>
<pre><code>## # A tibble: 6 × 5
##   county             fips  candidate       state   votes
##   &lt;chr&gt;              &lt;chr&gt; &lt;chr&gt;           &lt;chr&gt;   &lt;dbl&gt;
## 1 Los Angeles County 6037  Hillary Clinton CA    2464364
## 2 Los Angeles County 6037  Donald Trump    CA     769743
## 3 Los Angeles County 6037  Gary Johnson    CA      88968
## 4 Los Angeles County 6037  Jill Stein      CA      76465
## 5 Los Angeles County 6037  Gloria La Riva  CA      21993
## 6 Cook County        17031 Hillary Clinton IL    1611946</code></pre>
<p>The meaning of each column in <code>election_raw</code> is self-evident except <code>fips</code>. The accronym is short for <a href="https://en.wikipedia.org/wiki/FIPS_county_code">Federal Information Processing Standard</a>. In this dataset, <code>fips</code> values denote the area (nationwide, statewide, or countywide) that each row of data represent.</p>
<p>Nationwide and statewide tallies are included as rows in <code>election_raw</code> with <code>county</code> values of <code>NA</code>. There are two kinds of these summary rows:</p>
<ul>
<li>Federal-level summary rows have a <code>fips</code> value of <code>US</code>.</li>
<li>State-level summary rows have the state name as the <code>fips</code> value.</li>
</ul>
<ol start="4" style="list-style-type: decimal">
<li>Inspect rows with <code>fips=2000</code>. Provide a reason for excluding them. Drop these observations – please write over <code>election_raw</code> – and report the data dimensions after removal.</li>
</ol>
<pre class="r"><code>election_raw %&gt;% 
  filter(fips == 2000)</code></pre>
<pre><code>## # A tibble: 6 × 5
##   county fips  candidate          state  votes
##   &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;              &lt;chr&gt;  &lt;dbl&gt;
## 1 &lt;NA&gt;   2000  Donald Trump       AK    163387
## 2 &lt;NA&gt;   2000  Hillary Clinton    AK    116454
## 3 &lt;NA&gt;   2000  Gary Johnson       AK     18725
## 4 &lt;NA&gt;   2000  Jill Stein         AK      5735
## 5 &lt;NA&gt;   2000  Darrell Castle     AK      3866
## 6 &lt;NA&gt;   2000  Rocky De La Fuente AK      1240</code></pre>
<p><strong>The only reason I see for exclusion is lack of county information and the <code>fips</code> value is identified as neither federal level (<code>fips</code> value of US) or state-level (<code>fips</code> value as the state).</strong></p>
<p><strong>Dimensions:</strong></p>
<pre class="r"><code># Drop observations

election_raw &lt;- election_raw %&gt;% 
  filter(fips != 2000)

dim(election_raw) </code></pre>
<pre><code>## [1] 18345     5</code></pre>
</div>
<div id="census-data" class="section level2">
<h2>Census data</h2>
<p>The first few rows and columns of the <code>census</code> data are shown below.</p>
<pre class="r"><code>census %&gt;% 
  select(1:6) %&gt;% 
  head()</code></pre>
<pre><code>## # A tibble: 6 × 6
##   CensusTract State   County  TotalPop   Men Women
##         &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  1001020100 Alabama Autauga     1948   940  1008
## 2  1001020200 Alabama Autauga     2156  1059  1097
## 3  1001020300 Alabama Autauga     2968  1364  1604
## 4  1001020400 Alabama Autauga     4423  2172  2251
## 5  1001020500 Alabama Autauga    10763  4922  5841
## 6  1001020600 Alabama Autauga     3851  1787  2064</code></pre>
<p>Variable descriptions are given in the <code>metadata</code> file. The variables shown above are:</p>
<pre class="r"><code>census_meta %&gt;% head() </code></pre>
<pre><code>## # A tibble: 6 × 3
##   variable       description                     type       
##   &lt;chr&gt;          &lt;chr&gt;                           &lt;chr&gt;      
## 1 &quot;CensusTract &quot; &quot; Census tract ID &quot;             &quot; numeric &quot;
## 2 &quot;State &quot;       &quot; State, DC, or Puerto Rico &quot;   &quot; string &quot; 
## 3 &quot;County &quot;      &quot; County or county equivalent &quot; &quot; string &quot; 
## 4 &quot;TotalPop &quot;    &quot; Total population &quot;            &quot; numeric &quot;
## 5 &quot;Men &quot;         &quot; Number of men &quot;               &quot; numeric &quot;
## 6 &quot;Women &quot;       &quot; Number of women &quot;             &quot; numeric &quot;</code></pre>
<div style="page-break-after: always;"></div>
</div>
<div id="data-preprocessing" class="section level2">
<h2>Data preprocessing</h2>
<ol start="5" style="list-style-type: decimal">
<li><p>Separate the rows of <code>election_raw</code> into separate federal-, state-, and county-level data frames:</p>
<ul>
<li><p>Store federal-level tallies as <code>election_federal</code>.</p></li>
<li><p>Store state-level tallies as <code>election_state</code>.</p></li>
<li><p>Store county-level tallies as <code>election</code>. Coerce the <code>fips</code> variable to numeric.</p></li>
</ul></li>
</ol>
<pre class="r"><code>election_federal &lt;- election_raw %&gt;% 
  filter(fips == &quot;US&quot;)

election_state &lt;- election_raw %&gt;% 
  filter(is.na(county)) %&gt;% 
  filter(fips != &quot;US&quot;)

election &lt;- election_raw %&gt;% 
  filter(fips != &quot;US&quot;) %&gt;% 
  filter(!is.na(county)) %&gt;% 
  mutate(fips = as.numeric(fips))</code></pre>
<p>Federal-Level Tallies (First 5 Rows):</p>
<pre class="r"><code>election_federal %&gt;% 
  head()</code></pre>
<pre><code>## # A tibble: 6 × 5
##   county fips  candidate       state    votes
##   &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;           &lt;chr&gt;    &lt;dbl&gt;
## 1 &lt;NA&gt;   US    Donald Trump    US    62984825
## 2 &lt;NA&gt;   US    Hillary Clinton US    65853516
## 3 &lt;NA&gt;   US    Gary Johnson    US     4489221
## 4 &lt;NA&gt;   US    Jill Stein      US     1429596
## 5 &lt;NA&gt;   US    Evan McMullin   US      510002
## 6 &lt;NA&gt;   US    Darrell Castle  US      186545</code></pre>
<p>State-Level Tallies (First 5 Rows):</p>
<pre class="r"><code>election_state %&gt;% 
  head() </code></pre>
<pre><code>## # A tibble: 6 × 5
##   county fips  candidate       state   votes
##   &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;           &lt;chr&gt;   &lt;dbl&gt;
## 1 &lt;NA&gt;   CA    Hillary Clinton CA    8753788
## 2 &lt;NA&gt;   CA    Donald Trump    CA    4483810
## 3 &lt;NA&gt;   CA    Gary Johnson    CA     478500
## 4 &lt;NA&gt;   CA    Jill Stein      CA     278657
## 5 &lt;NA&gt;   CA    Gloria La Riva  CA      66101
## 6 &lt;NA&gt;   FL    Donald Trump    FL    4617886</code></pre>
<p>County-Level Tallies (First 5 Rows):</p>
<pre class="r"><code>election %&gt;% 
  head() </code></pre>
<pre><code>## # A tibble: 6 × 5
##   county              fips candidate       state   votes
##   &lt;chr&gt;              &lt;dbl&gt; &lt;chr&gt;           &lt;chr&gt;   &lt;dbl&gt;
## 1 Los Angeles County  6037 Hillary Clinton CA    2464364
## 2 Los Angeles County  6037 Donald Trump    CA     769743
## 3 Los Angeles County  6037 Gary Johnson    CA      88968
## 4 Los Angeles County  6037 Jill Stein      CA      76465
## 5 Los Angeles County  6037 Gloria La Riva  CA      21993
## 6 Cook County        17031 Hillary Clinton IL    1611946</code></pre>
<ol start="6" style="list-style-type: decimal">
<li>How many named presidential candidates were there in the 2016 election? Draw a bar graph of all votes received by each candidate, and order the candidate names by decreasing vote counts. (You may need to log-transform the vote axis.)</li>
</ol>
<pre class="r"><code>pres_ct &lt;- election_federal %&gt;% 
  filter(candidate != &quot; None of these candidates&quot;) %&gt;% 
  group_by(candidate) %&gt;% 
  mutate(sum = sum(votes)) %&gt;% 
  select(candidate, sum) %&gt;% 
  mutate(candidate = as.factor(candidate))
  

pres_ct %&gt;% 
  ggplot(aes(x = reorder(candidate, sum), y = log(sum), fill = candidate)) +
  geom_bar(colour = &quot;black&quot;, stat = &quot;identity&quot;) +
  guides(x = guide_axis(angle = 90), fill = FALSE) +
  labs(x = &quot;Candidate&quot;, y = &quot;Votes&quot;, title = &quot;Vote Counts (Log-Transformed) of Each Presidential Candidate, 2016&quot;) +
  coord_flip()</code></pre>
<p><img src="https://www.dina-arch.com/collection/machine-learning-final-project/index_files/figure-html/unnamed-chunk-11-1.png" width="576" style="display: block; margin: auto;" />
<strong>There are 31 named presidential candidates</strong></p>
<ol start="7" style="list-style-type: decimal">
<li>Create <code>county_winner</code> and <code>state_winner</code> by taking the candidate with the highest proportion of votes. (Hint: to create <code>county_winner</code>, start with <code>election</code>, group by <code>fips</code>, compute <code>total</code> votes, and <code>pct = votes/total</code>. Then choose the highest row using <code>slice_max</code> (variable <code>state_winner</code> is similar).)</li>
</ol>
<pre class="r"><code>county_winner &lt;- election %&gt;% 
  group_by(fips) %&gt;% 
  mutate(total = sum(votes)) %&gt;% 
  mutate(pct = votes/total) %&gt;% 
  slice_max(pct, n=1)

state_winner &lt;- election_state %&gt;% 
  group_by(fips) %&gt;% 
  mutate(total = sum(votes)) %&gt;% 
  mutate(pct = votes/total) %&gt;% 
  slice_max(pct, n=1)</code></pre>
<p>County Winner:</p>
<pre class="r"><code>county_winner %&gt;% 
  ungroup() %&gt;% 
  slice_max(pct, n=1)</code></pre>
<pre><code>## # A tibble: 1 × 7
##   county          fips candidate    state votes total   pct
##   &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Roberts County 48393 Donald Trump TX      524   550 0.953</code></pre>
<p>State Winner:</p>
<pre class="r"><code>state_winner %&gt;% 
  ungroup() %&gt;% 
  slice_max(pct, n=1)</code></pre>
<pre><code>## # A tibble: 1 × 7
##   county fips  candidate       state  votes  total   pct
##   &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;           &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
## 1 &lt;NA&gt;   DC    Hillary Clinton DC    282830 304717 0.928</code></pre>
</div>
</div>
<div id="visualization" class="section level1">
<h1>Visualization</h1>
<p>Here you’ll generate maps of the election data using <code>ggmap</code>. The .Rmd file for this document contains codes to generate the following map.</p>
<pre class="r"><code>states &lt;- map_data(&quot;state&quot;)

ggplot(states) + 
  geom_polygon(aes(x = long, 
                   y = lat, 
                   fill = region, 
                   group = group), 
               color = &quot;white&quot;) + 
  coord_fixed(1.3) + # avoid stretching
  guides(fill=FALSE) + # no fill legend
  theme_nothing() # no axes</code></pre>
<p><img src="https://www.dina-arch.com/collection/machine-learning-final-project/index_files/figure-html/unnamed-chunk-15-1.png" width="576" style="display: block; margin: auto;" /></p>
<ol start="8" style="list-style-type: decimal">
<li>Draw a county-level map with <code>map_data("county")</code> and color by county.</li>
</ol>
<pre class="r"><code>counties &lt;- map_data(&quot;county&quot;)

ggplot(counties) + 
  geom_polygon(aes(x = long, 
                   y = lat, 
                   fill = region, 
                   group = group), 
               color = &quot;white&quot;) + 
  coord_fixed(1.3) + # avoid stretching
  guides(fill=FALSE) + # no fill legend
  theme_nothing() # no axes</code></pre>
<p><img src="https://www.dina-arch.com/collection/machine-learning-final-project/index_files/figure-html/unnamed-chunk-16-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>In order to map the winning candidate for each state, the map data (<code>states</code>) must be merged with with the election data (<code>state_winner</code>).</p>
<p>The function <code>left_join()</code> will do the trick, but needs to join the data frames on a variable with values that match. In this case, that variable is the state name, but abbreviations are used in one data frame and the full name is used in the other.</p>
<ol start="9" style="list-style-type: decimal">
<li>Use the following function to create a <code>fips</code> variable in the <code>states</code> data frame with values that match the <code>fips</code> variable in <code>election_federal</code>.</li>
</ol>
<pre class="r"><code>name2abb &lt;- function(statename){
  ix &lt;- match(statename, tolower(state.name))
  out &lt;- state.abb[ix]
  return(out)
}
states &lt;- states %&gt;% 
  mutate(fips = name2abb(region))</code></pre>
<p>First 5 rows in the <code>states</code> data frame:</p>
<pre class="r"><code>states %&gt;% 
  head() </code></pre>
<pre><code>##        long      lat group order  region subregion fips
## 1 -87.46201 30.38968     1     1 alabama      &lt;NA&gt;   AL
## 2 -87.48493 30.37249     1     2 alabama      &lt;NA&gt;   AL
## 3 -87.52503 30.37249     1     3 alabama      &lt;NA&gt;   AL
## 4 -87.53076 30.33239     1     4 alabama      &lt;NA&gt;   AL
## 5 -87.57087 30.32665     1     5 alabama      &lt;NA&gt;   AL
## 6 -87.58806 30.32665     1     6 alabama      &lt;NA&gt;   AL</code></pre>
<ul>
<li>Now the data frames can be merged. <code>left_join(df1, df2)</code> takes all the rows from <code>df1</code> and looks for matches in <code>df2</code>. For each match, <code>left_join()</code> appends the data from the second table to the matching row in the first; if no matching value is found, it adds missing values.</li>
</ul>
<ol start="10" style="list-style-type: decimal">
<li>Use <code>left_join</code> to merge the tables and use the result to create a map of the election results by state. Your figure will look similar to this state level <a href="https://www.nytimes.com/elections/results/president">New York Times map</a>. (Hint: use <code>scale_fill_brewer(palette="Set1")</code> for a red-and-blue map.)</li>
</ol>
<p>Merged states by <code>fips</code> (First 5 rows):</p>
<pre class="r"><code>merged_states &lt;- left_join(states, state_winner) 

ggplot(merged_states) + 
  geom_polygon(aes(x = long, 
                   y = lat, 
                   fill = candidate, 
                   group = group), 
               color = &quot;Black&quot;) + 
  coord_fixed(1.3) + # avoid stretching
  guides(fill=FALSE) + # no fill legend
  theme_nothing() + # no axes
  scale_fill_brewer(palette=&quot;Set1&quot;) </code></pre>
<p><img src="https://www.dina-arch.com/collection/machine-learning-final-project/index_files/figure-html/unnamed-chunk-19-1.png" width="576" style="display: block; margin: auto;" /></p>
<ol start="11" style="list-style-type: decimal">
<li>Now create a county-level map. The county-level map data does not have a <code>fips</code> value, so to create one, use information from <code>maps::county.fips</code>: split the <code>polyname</code> column to <code>region</code> and <code>subregion</code> using <code>tidyr::separate</code>, and use <code>left_join()</code> to combine <code>county.fips</code> with the county-level map data. Then construct the map. Your figure will look similar to county-level <a href="https://www.nytimes.com/elections/results/president">New York Times map</a>.</li>
</ol>
<pre class="r"><code>county_fips &lt;- maps::county.fips %&gt;% 
  tidyr::separate(polyname, c(&quot;region&quot;, &quot;subregion&quot;), sep = &quot;,&quot;)

counties &lt;- left_join(counties, county_fips)

county_map &lt;- left_join(counties, county_winner)

ggplot(county_map) + 
  geom_polygon(aes(x = long, 
                   y = lat, 
                   fill = candidate, 
                   group = group), 
               color = &quot;white&quot;) + 
  coord_fixed(1.3) + # avoid stretching
  guides(fill=FALSE) + # no fill legend
  theme_nothing() + # no axes
  scale_fill_brewer(palette=&quot;Set1&quot;) </code></pre>
<p><img src="https://www.dina-arch.com/collection/machine-learning-final-project/index_files/figure-html/unnamed-chunk-20-1.png" width="576" style="display: block; margin: auto;" /></p>
<ol start="12" style="list-style-type: decimal">
<li>Create a visualization of your choice using <code>census</code> data. Many exit polls noted that <a href="https://fivethirtyeight.com/features/demographics-not-hacking-explain-the-election-results/">demographics played a big role in the election</a>. If you need a starting point, use <a href="https://www.washingtonpost.com/graphics/politics/2016-election/exit-polls/">this Washington Post article</a> and <a href="https://www.r-graph-gallery.com/">this R graph gallery</a> for ideas and inspiration.</li>
</ol>
<pre class="r"><code>census_12 &lt;- census %&gt;% 
  select(State, Men, Women, TotalPop, Income, Unemployment, Hispanic, White, Black) %&gt;%
  group_by(State) %&gt;% 
  summarise(across(Men:Income, ~ sum(.x, na.rm = TRUE)),
            across(Unemployment:Black, ~ mean(.x, na.rm = TRUE)))

p &lt;- census_12 %&gt;% 
  mutate(State = as.factor(State)) %&gt;% 
  group_by(State) %&gt;% 
  ggplot(aes(x = Unemployment, y = Income, size = TotalPop, fill = State, colour = State)) + 
  geom_point(show.legend = FALSE) +
  geom_text(label=census_12$State, 
            nudge_x = 0.25, 
            nudge_y = 0.25, 
            check_overlap = F,
            colour = &quot;Black&quot;)

p </code></pre>
<p><img src="https://www.dina-arch.com/collection/machine-learning-final-project/index_files/figure-html/unnamed-chunk-21-1.png" width="1152" style="display: block; margin: auto;" /></p>
<ol start="13" style="list-style-type: decimal">
<li>The <code>census</code> data contains high resolution information (more fine-grained than county-level). Aggregate the information into county-level data by computing population-weighted averages of each attribute for each county by carrying out the following steps:</li>
</ol>
<ul>
<li><p>Clean census data, saving the result as <code>census_del</code>:</p>
<ul>
<li>filter out any rows of <code>census</code> with missing values;</li>
<li>convert <code>Men</code>, <code>Employed</code>, and <code>Citizen</code> to percentages;</li>
<li>compute a <code>Minority</code> variable by combining <code>Hispanic</code>, <code>Black</code>, <code>Native</code>, <code>Asian</code>, <code>Pacific</code>, and remove these variables after creating <code>Minority</code>; and</li>
<li>remove <code>Walk</code>, <code>PublicWork</code>, and <code>Construction</code>.</li>
</ul></li>
</ul>
<pre class="r"><code>census_del &lt;- census %&gt;% 
  drop_na() %&gt;% 
  mutate(Men = (Men/TotalPop)*100,
         Citizen = (Citizen/TotalPop)*100, 
         Employed = (Employed/TotalPop)*100) %&gt;%
  mutate(Minority = rowSums(across(c(Hispanic, Black, Native, Asian, Pacific)))) %&gt;% 
  select(-Hispanic, -Black, -Native, -Asian, -Pacific, -Walk, -PublicWork, -Construction)</code></pre>
<ul>
<li>Create population weights for sub-county census data, saving the result as <code>census_subct</code>:
<ul>
<li>group <code>census_del</code> by <code>State</code> and <code>County</code>;</li>
<li>use <code>add_tally()</code> to compute <code>CountyPop</code>;</li>
<li>compute the population weight as <code>TotalPop/CountyTotal</code>;</li>
<li>adjust all quantitative variables by multiplying by the population weights.</li>
</ul></li>
</ul>
<pre class="r"><code>census_subct &lt;- census_del %&gt;% 
  group_by(State, County) %&gt;% 
  mutate(CountyPop = sum(TotalPop)) %&gt;% 
  mutate(PopWeight = TotalPop/CountyPop) %&gt;% 
  mutate(across(Men:Minority, ~.x*PopWeight))</code></pre>
<ul>
<li>Aggregate census data to county level, <code>census_ct</code>: group the sub-county data <code>census_subct</code> by state and county and compute popluation-weighted averages of each variable by taking the sum (since the variables were already transformed by the population weights)</li>
</ul>
<pre class="r"><code>census_ct &lt;- census_subct %&gt;% 
  group_by(State, County) %&gt;% 
  summarise(across(Men:Minority, sum))</code></pre>
<ul>
<li>Print the first few rows and columns of <code>census_ct</code>.</li>
</ul>
<pre class="r"><code>census_ct %&gt;% 
  head()</code></pre>
<pre><code>## # A tibble: 6 × 28
## # Groups:   State [1]
##   State   County    Men Women White Citizen Income IncomeErr IncomePerCap
##   &lt;chr&gt;   &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;        &lt;dbl&gt;
## 1 Alabama Autauga  48.4 3349.  75.8    73.7 51696.     7771.       24974.
## 2 Alabama Baldwin  48.8 3934.  83.1    75.7 51074.     8745.       27317.
## 3 Alabama Barbour  53.8 1492.  46.2    76.9 32959.     6031.       16824.
## 4 Alabama Bibb     53.4 2930.  74.5    77.4 38887.     5662.       18431.
## 5 Alabama Blount   49.4 3562.  87.9    73.4 46238.     8696.       20532.
## 6 Alabama Bullock  53.0 1968.  22.2    75.5 33293.     9000.       17580.
## # … with 19 more variables: IncomePerCapErr &lt;dbl&gt;, Poverty &lt;dbl&gt;,
## #   ChildPoverty &lt;dbl&gt;, Professional &lt;dbl&gt;, Service &lt;dbl&gt;, Office &lt;dbl&gt;,
## #   Production &lt;dbl&gt;, Drive &lt;dbl&gt;, Carpool &lt;dbl&gt;, Transit &lt;dbl&gt;,
## #   OtherTransp &lt;dbl&gt;, WorkAtHome &lt;dbl&gt;, MeanCommute &lt;dbl&gt;, Employed &lt;dbl&gt;,
## #   PrivateWork &lt;dbl&gt;, SelfEmployed &lt;dbl&gt;, FamilyWork &lt;dbl&gt;,
## #   Unemployment &lt;dbl&gt;, Minority &lt;dbl&gt;</code></pre>
<ol start="14" style="list-style-type: decimal">
<li>If you were physically located in the United States on election day for the 2016 presidential election, what state and county were you in? Compare and contrast the results and demographic information for this county with the state it is located in. If you were not in the United States on election day, select any county. Do you find anything unusual or surprising? If so, explain; if not, explain why not.</li>
</ol>
<p><strong>On election day, I was in Los Angeles, CA. Taking the average values of some of the variables to look at overall California demographics, it looks like minorities make up 70% of LA, and 40% of California. Men and Unemployement is unchanged. Having lived here a long time, I am not surprised at the demographics. LA is much more diverse than the rest of California.</strong></p>
<pre class="r"><code>census_ct %&gt;% 
  filter(County == &quot;Los Angeles&quot;)</code></pre>
<pre><code>## # A tibble: 1 × 28
## # Groups:   State [1]
##   State      County        Men Women White Citizen Income IncomeErr IncomePerCap
##   &lt;chr&gt;      &lt;chr&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;        &lt;dbl&gt;
## 1 California Los Angeles  49.2 2460.  26.9    60.1 61385.    10572.       28390.
## # … with 19 more variables: IncomePerCapErr &lt;dbl&gt;, Poverty &lt;dbl&gt;,
## #   ChildPoverty &lt;dbl&gt;, Professional &lt;dbl&gt;, Service &lt;dbl&gt;, Office &lt;dbl&gt;,
## #   Production &lt;dbl&gt;, Drive &lt;dbl&gt;, Carpool &lt;dbl&gt;, Transit &lt;dbl&gt;,
## #   OtherTransp &lt;dbl&gt;, WorkAtHome &lt;dbl&gt;, MeanCommute &lt;dbl&gt;, Employed &lt;dbl&gt;,
## #   PrivateWork &lt;dbl&gt;, SelfEmployed &lt;dbl&gt;, FamilyWork &lt;dbl&gt;,
## #   Unemployment &lt;dbl&gt;, Minority &lt;dbl&gt;</code></pre>
<pre class="r"><code>census_ct %&gt;% 
  filter(State == &quot;California&quot;) %&gt;%
  summarise(across(Men:Minority, mean)) </code></pre>
<pre><code>## # A tibble: 1 × 27
##   State    Men Women White Citizen Income IncomeErr IncomePerCap IncomePerCapErr
##   &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;        &lt;dbl&gt;           &lt;dbl&gt;
## 1 Calif…  50.4 2665.  55.7    68.2 59031.     9828.       28014.           3977.
## # … with 18 more variables: Poverty &lt;dbl&gt;, ChildPoverty &lt;dbl&gt;,
## #   Professional &lt;dbl&gt;, Service &lt;dbl&gt;, Office &lt;dbl&gt;, Production &lt;dbl&gt;,
## #   Drive &lt;dbl&gt;, Carpool &lt;dbl&gt;, Transit &lt;dbl&gt;, OtherTransp &lt;dbl&gt;,
## #   WorkAtHome &lt;dbl&gt;, MeanCommute &lt;dbl&gt;, Employed &lt;dbl&gt;, PrivateWork &lt;dbl&gt;,
## #   SelfEmployed &lt;dbl&gt;, FamilyWork &lt;dbl&gt;, Unemployment &lt;dbl&gt;, Minority &lt;dbl&gt;</code></pre>
</div>
<div id="exploratory-analysis" class="section level1">
<h1>Exploratory analysis</h1>
<ol start="15" style="list-style-type: decimal">
<li>Carry out PCA for both county &amp; sub-county level census data. Compute the first two principal components PC1 and PC2 for both county and sub-county respectively. Discuss whether you chose to center and scale the features and the reasons for your choice. Examine and interpret the loadings.</li>
</ol>
<p>County Level:</p>
<pre class="r"><code># County Level Census

# Center and scale the data
county_std &lt;- census_ct %&gt;% 
  as.data.frame() %&gt;% 
  select(-c(&#39;State&#39;,&#39;County&#39;)) %&gt;% 
  scale(center = T, scale = T)


# Compute SVD
x_svd &lt;- svd(county_std)

# Get loadings
v_svd &lt;- x_svd$v

# compute principal components
county_pc &lt;- county_std %*% v_svd
colnames(county_pc) &lt;- paste(&#39;PC&#39;, 1:26, sep = &#39;&#39;)

# scatterplot
as_tibble(county_pc[,1:2]) %&gt;%
  bind_cols(select(census_ct, County)) %&gt;% 
  ggplot(aes(x = PC1, y = PC2)) +
  geom_point(aes(color = County)) +
  theme_bw() +
  theme(legend.position=&quot;none&quot;)</code></pre>
<p><img src="https://www.dina-arch.com/collection/machine-learning-final-project/index_files/figure-html/unnamed-chunk-27-1.png" width="576" style="display: block; margin: auto;" /></p>
<pre class="r"><code>v_svd[, 1:2] %&gt;%
  as.data.frame() %&gt;%
  mutate(variable = colnames(county_std)) %&gt;%
  gather(key = &#39;PC&#39;, value = &#39;Loading&#39;, 1:2) %&gt;%
  arrange(variable) %&gt;%
  ggplot(aes(x = variable, y = Loading)) +
  geom_point(aes(shape = PC)) +
  theme_bw() +
  geom_hline(yintercept = 0, color = &#39;blue&#39;) +
  geom_path(aes(linetype = PC, group = PC)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = &#39;&#39;) </code></pre>
<p><img src="https://www.dina-arch.com/collection/machine-learning-final-project/index_files/figure-html/unnamed-chunk-27-2.png" width="576" style="display: block; margin: auto;" /></p>
<pre class="r"><code>v_svd[, 1:2] %&gt;%
  as.data.frame() %&gt;%
  mutate(variable = colnames(county_std)) %&gt;%
  gather(key = &#39;PC&#39;, value = &#39;Loading&#39;, 1:2) %&gt;%
  arrange(variable) %&gt;%
  ggplot(aes(x = variable, y = Loading)) +
  geom_point(aes(shape = PC)) +
  theme_bw() +
  geom_hline(yintercept = 0, color = &#39;blue&#39;) +
  geom_path(aes(linetype = PC, group = PC)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = &#39;&#39;) +
  facet_wrap(~PC)</code></pre>
<p><img src="https://www.dina-arch.com/collection/machine-learning-final-project/index_files/figure-html/unnamed-chunk-27-3.png" width="576" style="display: block; margin: auto;" /></p>
<p><strong>The first PC has a high percentage of children under poverty level, a high percentage of people under poverty level, and high percentage of those unemployed. The first PC also has low income per capital, low percentage of those employed (16+), and low median household income. I would label this principal component as <em>Under Poverty Level</em>.</strong></p>
<p><strong>The second PC has a high percentage of those who are self-employed, a high percentage of those working at home, and high percentage of those working in unpaid family work. The second PC also has low number of women, low percentage of working in private industry, and low percentage of employed in office jobs. I would label this principal component as <em>Working Class - Family Oriented</em>.</strong></p>
<p>Sub-county Level:</p>
<pre class="r"><code># Sub-County Level Census

# Center and scale the data
subcounty_std &lt;- census_subct %&gt;% 
  as.data.frame() %&gt;% 
  select(-c(&#39;State&#39;,&#39;County&#39;,&#39;CensusTract&#39;, &#39;PopWeight&#39;, &#39;TotalPop&#39;, &#39;CountyPop&#39;)) %&gt;% 
  scale(center = T, scale = T)


# Compute SVD
x_svd2 &lt;- svd(subcounty_std)

# Get loadings
v_svd2 &lt;- x_svd2$v

# compute principal components
subcounty_pc &lt;- subcounty_std %*% v_svd2
colnames(subcounty_pc) &lt;- paste(&#39;PC&#39;, 1:26, sep = &#39;&#39;)

# scatterplot
as_tibble(subcounty_pc[,1:2]) %&gt;%
  bind_cols(select(census_subct, County)) %&gt;% 
  ggplot(aes(x = PC1, y = PC2)) +
  geom_point(aes(color = County)) +
  theme_bw() +
  theme(legend.position=&quot;none&quot;)</code></pre>
<p><img src="https://www.dina-arch.com/collection/machine-learning-final-project/index_files/figure-html/unnamed-chunk-28-1.png" width="576" style="display: block; margin: auto;" /></p>
<pre class="r"><code>v_svd2[, 1:2] %&gt;%
  as.data.frame() %&gt;%
  mutate(variable = colnames(subcounty_std)) %&gt;%
  gather(key = &#39;PC&#39;, value = &#39;Loading&#39;, 1:2) %&gt;%
  arrange(variable) %&gt;%
  ggplot(aes(x = variable, y = Loading)) +
  geom_point(aes(shape = PC)) +
  theme_bw() +
  geom_hline(yintercept = 0, color = &#39;blue&#39;) +
  geom_path(aes(linetype = PC, group = PC)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = &#39;&#39;) </code></pre>
<p><img src="https://www.dina-arch.com/collection/machine-learning-final-project/index_files/figure-html/unnamed-chunk-28-2.png" width="576" style="display: block; margin: auto;" /></p>
<pre class="r"><code>v_svd2[, 1:2] %&gt;%
  as.data.frame() %&gt;%
  mutate(variable = colnames(subcounty_std)) %&gt;%
  gather(key = &#39;PC&#39;, value = &#39;Loading&#39;, 1:2) %&gt;%
  arrange(variable) %&gt;%
  ggplot(aes(x = variable, y = Loading)) +
  geom_point(aes(shape = PC)) +
  theme_bw() +
  geom_hline(yintercept = 0, color = &#39;blue&#39;) +
  geom_path(aes(linetype = PC, group = PC)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = &#39;&#39;) +
  facet_wrap(~PC)</code></pre>
<p><img src="https://www.dina-arch.com/collection/machine-learning-final-project/index_files/figure-html/unnamed-chunk-28-3.png" width="576" style="display: block; margin: auto;" /></p>
<pre class="r"><code>data &lt;- v_svd2[, 1:2] %&gt;%
  as.data.frame() %&gt;% 
  mutate(variable = colnames(subcounty_std))</code></pre>
<p><strong>This PC is interesting because all 26 variables are positive and relatively high, where most have loadings greater than .20. The first PC has a high percentage of Men, a high number of citizens, high percentage of those employed in private industry, high percentage of those who commute alone in a car, and a high percentage of those employed (+16). I would label this principal component as <em>Working-Class</em>.</strong></p>
<p><strong>The second PC has a high percentage of minorities, a high percentage of unemployment, and high percentage of child poverty and under poverty level. The second PC also has low percentage of those who work from home, low percentage of inpaid family work, and low percentage of those who are self-employed. I would label this principal component as <em>Under Poverty Level</em>.</strong></p>
<p><strong>It’s usually important to both center and scale your variables as they are most likely not on the same metric. As in this case, I center and scaled the dataset because some variables are count and others are percentages. Either way, it doesn’t hurt.</strong></p>
<ol start="16" style="list-style-type: decimal">
<li>Determine the minimum number of PCs needed to capture 90% of the variance for both the county and sub-county analyses. Plot the proportion of variance explained and cumulative variance explained for both county and sub-county analyses.</li>
</ol>
<p>County Level:</p>
<pre class="r"><code># scree and cumulative variance plots
pc_vars &lt;- x_svd$d^2/(nrow(county_std) - 1)

tibble(PC = 1:min(dim(county_std)),
       Proportion = pc_vars/sum(pc_vars),
       Cumulative = cumsum(Proportion)) %&gt;%
  gather(key = &#39;measure&#39;, value = &#39;Variance Explained&#39;, 2:3) %&gt;%
  ggplot(aes(x = PC, y = `Variance Explained`)) +
  geom_point() +
  geom_path() +
  facet_wrap(~ measure) +
  theme_bw() </code></pre>
<p><img src="https://www.dina-arch.com/collection/machine-learning-final-project/index_files/figure-html/unnamed-chunk-29-1.png" width="576" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#tibble(PC = 1:min(dim(county_std)),
#       Proportion = pc_vars/sum(pc_vars),
#       Cumulative = cumsum(Proportion)) %&gt;% 
#  head(15) %&gt;% 
#  pander()</code></pre>
<p><strong>At least <em>13</em> PCs are needed to capture 90% of the variance for the county analysis.</strong></p>
<p>Sub-County Level:</p>
<pre class="r"><code># scree and cumulative variance plots
pc_vars2 &lt;- x_svd2$d^2/(nrow(subcounty_std) - 1)

tibble(PC = 1:min(dim(subcounty_std)),
       Proportion = pc_vars2/sum(pc_vars2),
       Cumulative = cumsum(Proportion)) %&gt;%
  gather(key = &#39;measure&#39;, value = &#39;Variance Explained&#39;, 2:3) %&gt;%
  ggplot(aes(x = PC, y = `Variance Explained`)) +
  geom_point() +
  geom_path() +
  facet_wrap(~ measure) +
  theme_bw() </code></pre>
<p><img src="https://www.dina-arch.com/collection/machine-learning-final-project/index_files/figure-html/unnamed-chunk-30-1.png" width="576" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#tibble(PC = 1:min(dim(subcounty_std)),
#       Proportion = pc_vars2/sum(pc_vars2),
#       Cumulative = cumsum(Proportion)) %&gt;% 
#  head(10) %&gt;% 
#  pander()</code></pre>
<p><strong>At least <em>7</em> PCs are needed to capture 90% of the variance for the sub-county analysis.</strong></p>
<ol start="17" style="list-style-type: decimal">
<li>With <code>census_ct</code>, perform hierarchical clustering with complete linkage. Cut the tree to partition the observations into 10 clusters. Re-run the hierarchical clustering algorithm using the first 5 principal components the county-level data as inputs instead of the original features. Compare and contrast the results. For both approaches investigate the cluster that contains San Mateo County. Which approach seemed to put San Mateo County in a more appropriate cluster? Comment on what you observe and discuss possible explanations for these observations.</li>
</ol>
<p>Hierarchical Clustering:</p>
<pre class="r"><code>library(ggridges)
library(dendextend)
# compute distances between points
d_mx &lt;- dist(county_std, method = &#39;euclidean&#39;)

# compute hierarchical clustering
hclust_out &lt;- hclust(d_mx, method = &#39;complete&#39;)

# cut at 10 clusters
clusters &lt;- cutree(hclust_out, k = 10) %&gt;% 
  factor(labels = paste(&#39;cluster&#39;, 1:10))

# count number of data points per cluster
tibble(clusters) %&gt;% 
  count(clusters) </code></pre>
<pre><code>## # A tibble: 10 × 2
##    clusters       n
##    &lt;fct&gt;      &lt;int&gt;
##  1 cluster 1   2307
##  2 cluster 2    779
##  3 cluster 3     67
##  4 cluster 4      8
##  5 cluster 5     20
##  6 cluster 6      4
##  7 cluster 7      3
##  8 cluster 8      3
##  9 cluster 9     23
## 10 cluster 10     4</code></pre>
<p>Cluster for San Mateo County:</p>
<pre class="r"><code>#filter San Mateo County
san_mateo &lt;- which(grepl(&#39;San Mateo&#39;, census_ct$County))
clusters[san_mateo]</code></pre>
<pre><code>## [1] cluster 1
## 10 Levels: cluster 1 cluster 2 cluster 3 cluster 4 cluster 5 ... cluster 10</code></pre>
<p>Hierarchical Clustering for first five PCs:</p>
<pre class="r"><code># First 5 PC

# compute distances between points
d_mx &lt;- dist(county_pc[,1:5], method = &#39;euclidean&#39;)

# compute hierarchical clustering
hclust_out &lt;- hclust(d_mx, method = &#39;complete&#39;)

# cut at 10 clusters
clusters &lt;- cutree(hclust_out, k = 10) %&gt;% 
  factor(labels = paste(&#39;cluster&#39;, 1:10))

# count number of data points per cluster
tibble(clusters) %&gt;% 
  count(clusters)</code></pre>
<pre><code>## # A tibble: 10 × 2
##    clusters       n
##    &lt;fct&gt;      &lt;int&gt;
##  1 cluster 1   1950
##  2 cluster 2    631
##  3 cluster 3    312
##  4 cluster 4     57
##  5 cluster 5      8
##  6 cluster 6    167
##  7 cluster 7     43
##  8 cluster 8      7
##  9 cluster 9     40
## 10 cluster 10     3</code></pre>
<p>Cluster for San Mateo County:</p>
<pre class="r"><code>#filter San Mateo County
san_mateo &lt;- which(grepl(&#39;San Mateo&#39;, census_ct$County))
clusters[san_mateo] </code></pre>
<pre><code>## [1] cluster 3
## 10 Levels: cluster 1 cluster 2 cluster 3 cluster 4 cluster 5 ... cluster 10</code></pre>
<p><strong>It seems that the counties in the PC cluster are more evenly spread out than using the entire dataset. When using the first 5 principal components, we are capturing 64% of the variance in the county dataset with only five variables. Because of the smaller dimension, it may be more effective in clustering the counties as opposed to using 26 variables with the full dataset. It makes sense that San Mateo county is put into cluster 1 with the full dataset as most counties are grouped there. Thus, we may want to rely on the cluster that used the PCs, where San Mateo is in cluster 3.</strong></p>
</div>
<div id="classification" class="section level1">
<h1>Classification</h1>
<p>In order to train classification models, we need to combine <code>county_winner</code> and <code>census_ct</code> data. This seemingly straightforward task is harder than it sounds. Codes are provided in the .Rmd file that make the necessary changes to merge them into <code>election_cl</code> for classification.</p>
<pre class="r"><code>abb2name &lt;- function(stateabb){
  ix &lt;- match(stateabb, state.abb)
  out &lt;- tolower(state.name[ix])
  return(out)
}


tmpwinner &lt;- county_winner %&gt;%
  ungroup %&gt;%
  # coerce names to abbreviations
  mutate(state = abb2name(state)) %&gt;%
  # everything lower case
  mutate(across(c(state, county), tolower)) %&gt;%
  # remove county suffixes
  mutate(county = gsub(&quot; county| columbia| city| parish&quot;, 
                       &quot;&quot;, 
                       county)) 

tmpcensus &lt;- census_ct %&gt;% 
  ungroup %&gt;% 
  mutate(across(c(State, County), tolower))

election_county &lt;- tmpwinner %&gt;%
  left_join(tmpcensus, 
            by = c(&quot;state&quot;=&quot;State&quot;, &quot;county&quot;=&quot;County&quot;)) %&gt;% 
  na.omit()

## save meta information
election_meta &lt;- election_county %&gt;% 
  select(c(county, fips, state, votes, pct, total))

## save predictors and class labels
election_county &lt;- election_county %&gt;% 
  select(-c(county, fips, state, votes, pct, total))</code></pre>
<p>After merging the data, partition the result into 80% training and 20% testing partitions.</p>
<pre class="r"><code># hold out 20% of data as a test set
set.seed(12521)
county_part &lt;- resample_partition(election_county, c(test = 0.2, train = 0.8))
train &lt;- as_tibble(county_part$train)
test &lt;- as_tibble(county_part$test)</code></pre>
<ol start="18" style="list-style-type: decimal">
<li>Decision tree: train a decision tree on the training partition, and apply cost-complexity pruning. Visualize the tree before and after pruning. Estimate the misclassification errors on the test partition, and interpret and discuss the results of the decision tree analysis. Use your plot to tell a story about voting behavior in the US (see this <a href="https://archive.nytimes.com/www.nytimes.com/imagepages/2008/04/16/us/20080416_OBAMA_GRAPHIC.html">NYT infographic</a>).</li>
</ol>
<pre class="r"><code>#Train a decision tree - training partition
nmin &lt;- 5
tree_opts &lt;- tree.control(nobs = nrow(train), 
                          minsize = nmin, 
                          mindev = exp(-6))
t_small &lt;- tree(as.factor(candidate) ~ ., data = train,
                control = tree_opts, split = &#39;deviance&#39;) 
summary(t_small)</code></pre>
<pre><code>## 
## Classification tree:
## tree(formula = as.factor(candidate) ~ ., data = train, control = tree_opts, 
##     split = &quot;deviance&quot;)
## Variables actually used in tree construction:
##  [1] &quot;White&quot;           &quot;Men&quot;             &quot;Unemployment&quot;    &quot;IncomePerCapErr&quot;
##  [5] &quot;MeanCommute&quot;     &quot;Service&quot;         &quot;Women&quot;           &quot;Citizen&quot;        
##  [9] &quot;IncomePerCap&quot;    &quot;Drive&quot;           &quot;Transit&quot;         &quot;Office&quot;         
## [13] &quot;Production&quot;      &quot;SelfEmployed&quot;    &quot;Income&quot;          &quot;WorkAtHome&quot;     
## [17] &quot;Poverty&quot;         &quot;Employed&quot;        &quot;Carpool&quot;         &quot;Professional&quot;   
## [21] &quot;PrivateWork&quot;     &quot;OtherTransp&quot;     &quot;FamilyWork&quot;     
## Number of terminal nodes:  84 
## Residual mean deviance:  0.04184 = 99.29 / 2373 
## Misclassification error rate: 0.008547 = 21 / 2457</code></pre>
<p>Tree before pruning:</p>
<pre class="r"><code>draw.tree(t_small, cex = 0.5, size = 2)</code></pre>
<p><img src="https://www.dina-arch.com/collection/machine-learning-final-project/index_files/figure-html/unnamed-chunk-38-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>Add cost-complexity pruning:</p>
<pre class="r"><code># cost-complexity pruning
nfolds &lt;- 10
cv_out &lt;- cv.tree(t_small, K = nfolds, method = &#39;deviance&#39;)

# convert to tibble
cv_df &lt;- tibble(alpha = cv_out$k,
                impurity = cv_out$dev,
                size = cv_out$size)

# choose optimal alpha
best_alpha &lt;- slice_min(cv_df, impurity) %&gt;%
  slice_min(size)

# select final tree
t_opt &lt;- prune.tree(t_small, k = best_alpha$alpha)
summary(t_opt) </code></pre>
<pre><code>## 
## Classification tree:
## snip.tree(tree = t_small, nodes = c(4L, 14L, 5L, 15L, 6L))
## Variables actually used in tree construction:
## [1] &quot;White&quot;        &quot;Men&quot;          &quot;Transit&quot;      &quot;Professional&quot;
## Number of terminal nodes:  5 
## Residual mean deviance:  0.4521 = 1108 / 2452 
## Misclassification error rate: 0.0814 = 200 / 2457</code></pre>
<p>Tree after pruning:</p>
<pre class="r"><code>draw.tree(t_opt, cex = 0.8, size = 2)</code></pre>
<p><img src="https://www.dina-arch.com/collection/machine-learning-final-project/index_files/figure-html/unnamed-chunk-40-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>Classification Errors on Test Partition - Before Pruning:</p>
<pre class="r"><code># predict on test data
preds_test_t0 &lt;- predict(t_small, newdata = county_part$test, type = &#39;class&#39;)
# examin misclassification errors on test set - First Tree
classes_test &lt;- as.data.frame(county_part$test) %&gt;% pull(candidate)
test_errors_t0 &lt;- table(class = classes_test, pred = preds_test_t0)
(test_errors_t0/rowSums(test_errors_t0)) </code></pre>
<pre><code>##                  pred
## class             Donald Trump Hillary Clinton
##   Donald Trump       0.9496124       0.0503876
##   Hillary Clinton    0.3505155       0.6494845</code></pre>
<p>Classification Errors on Test Partition - After Pruning:</p>
<pre class="r"><code># predict on test data
preds_test_t0 &lt;- predict(t_opt, newdata = county_part$test, type = &#39;class&#39;)
# Pruned - Tree Error
classes_test &lt;- as.data.frame(county_part$test) %&gt;% pull(candidate)
test_errors_t0 &lt;- table(class = classes_test, pred = preds_test_t0)
(test_errors_t0/rowSums(test_errors_t0)) </code></pre>
<pre><code>##                  pred
## class             Donald Trump Hillary Clinton
##   Donald Trump      0.94379845      0.05620155
##   Hillary Clinton   0.44329897      0.55670103</code></pre>
<p><strong>After training a decision tree before pruning, the resulting classification tree had 84 terminal nodes and a misclassification error rate of 0.0085. There were 23 variables used. After pruning the classification tree, now there are 5 terminal nodes and a misclassifcation error rate of 0.0814. There were four variables used: White, Men, Transit, Professional. Similar to the infographic, it’s not surprising that “White” is used as the first splitting variable and Men is one of the second spliting variables. Counties that are less than 49.969% White and less than 49.6965 Male were likely to vote for Hillary Clinton. Which makes sense given the demographics of the election results, however it isn’t very telling as splitting on almost 50% isn’t much information. On the other side of the decision tree, counties that are more than almost 50% white, more than 1.138% use public transportation, and more than 35.4651% are employed in management positions voted for Hillary. It’s interesting that counties that have more than 1.138% of people using public transit are likely to vote Trump. It may indicate that the model needs some adjustments since the misclassification error rate is higher for this model.</strong></p>
<ol start="19" style="list-style-type: decimal">
<li>Train a logistic regression model on the training partition to predict the winning candidate in each county and estimate errors on the test partition. What are the significant variables? Are these consistent with what you observed in the decision tree analysis? Interpret the meaning of one or two significant coefficients of your choice in terms of a unit change in the variables. Did the results in your particular county (from question 14) match the predicted results?</li>
</ol>
<pre class="r"><code>fit_glm &lt;- glm(as.factor(candidate) ~ ., family = &#39;binomial&#39;, data=train)

summary(fit_glm)</code></pre>
<pre><code>## 
## Call:
## glm(formula = as.factor(candidate) ~ ., family = &quot;binomial&quot;, 
##     data = train)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.9700  -0.2610  -0.1094  -0.0414   3.5310  
## 
## Coefficients:
##                   Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)     -1.230e+01  9.576e+00  -1.284 0.199042    
## Men             -3.202e-02  5.466e-02  -0.586 0.558020    
## Women            4.849e-05  1.675e-04   0.289 0.772235    
## White           -1.876e-01  6.417e-02  -2.924 0.003453 ** 
## Citizen          1.139e-01  2.934e-02   3.881 0.000104 ***
## Income          -5.835e-05  2.752e-05  -2.120 0.033970 *  
## IncomeErr        4.269e-05  6.807e-05   0.627 0.530554    
## IncomePerCap     1.900e-04  6.601e-05   2.879 0.003991 ** 
## IncomePerCapErr -2.421e-04  1.405e-04  -1.723 0.084840 .  
## Poverty          4.498e-02  4.267e-02   1.054 0.291820    
## ChildPoverty    -4.893e-03  2.611e-02  -0.187 0.851348    
## Professional     2.568e-01  3.852e-02   6.665 2.64e-11 ***
## Service          3.509e-01  4.974e-02   7.055 1.73e-12 ***
## Office           1.209e-01  4.660e-02   2.595 0.009448 ** 
## Production       1.849e-01  4.262e-02   4.337 1.44e-05 ***
## Drive           -2.236e-01  4.639e-02  -4.821 1.43e-06 ***
## Carpool         -2.164e-01  6.138e-02  -3.525 0.000423 ***
## Transit          4.788e-02  9.227e-02   0.519 0.603815    
## OtherTransp     -9.843e-02  1.018e-01  -0.967 0.333650    
## WorkAtHome      -1.356e-01  7.447e-02  -1.821 0.068677 .  
## MeanCommute      5.417e-02  2.500e-02   2.167 0.030224 *  
## Employed         1.960e-01  3.376e-02   5.807 6.36e-09 ***
## PrivateWork      7.211e-02  2.230e-02   3.233 0.001224 ** 
## SelfEmployed     1.535e-02  4.992e-02   0.308 0.758415    
## FamilyWork      -8.790e-01  4.130e-01  -2.128 0.033336 *  
## Unemployment     1.742e-01  4.075e-02   4.275 1.91e-05 ***
## Minority        -6.081e-02  6.186e-02  -0.983 0.325579    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 2071.81  on 2456  degrees of freedom
## Residual deviance:  841.25  on 2430  degrees of freedom
## AIC: 895.25
## 
## Number of Fisher Scoring iterations: 7</code></pre>
<p>Errors (Test Partition):</p>
<pre class="r"><code># compute estimated probabilities
p_hat_glm &lt;- predict(fit_glm, test, type = &#39;response&#39;)

# bayes classifier
y_hat_glm &lt;- factor(p_hat_glm &gt; 0.5, labels = c(&#39;No&#39;, &#39;Yes&#39;))

# errors
error_glm &lt;- table(test$candidate, y_hat_glm)
(error_glm / rowSums(error_glm)) </code></pre>
<pre><code>##                  y_hat_glm
##                           No        Yes
##   Donald Trump    0.95930233 0.04069767
##   Hillary Clinton 0.32989691 0.67010309</code></pre>
<p><strong>Significant predictors of candidate are White, Citizen, Income, IncomePerCap, Professional, Service, Office, Production, Drive, Carpool, MeanCommute, Employed, PrivateWork, FamilyWork, and Unemployement. Only one of the variables overlap with the variables chosen in the pruned decision tree which is inconsistent.</strong></p>
<p><strong>The probability of a county voting for Donald Trump increases by an estimated 0.1139 among counties with Citizens, after accounting for all other predictors.</strong></p>
<p><strong>The probability of a county voting for Donald Trump decreases by an estimated -.879 among counties with unpaid family workers, after accounting for all other predictors.</strong></p>
<p><strong>Yes, the results in Los Angeles county (Hillary Clinton) matched the predicted results.</strong></p>
<ol start="20" style="list-style-type: decimal">
<li>Compute ROC curves for the decision tree and logistic regression using predictions on the test data, and display them on the same plot. Based on your classification results, discuss the pros and cons of each method. Are the different classifiers more appropriate for answering different kinds of questions about the election?</li>
</ol>
<p>Decision Tree:</p>
<pre class="r"><code>#Decision Tree
t_predict &lt;- predict(t_small, newdata = test) %&gt;% 
  as_tibble()

tree_predict &lt;- prediction(t_predict[,2], labels = test$candidate)

# compute error rates as a function of the probability threshold
perf_log &lt;- performance(prediction.obj = tree_predict, &#39;tpr&#39;, &#39;fpr&#39;)

# extract rates and threshold from perf_lda as a tibble
rates_log &lt;- tibble(fpr = perf_log@x.values,
                    tpr = perf_log@y.values,
                    thresh = perf_log@alpha.values) %&gt;%
  unnest(everything())

# compute youden&#39;s stat
rates_log &lt;- rates_log %&gt;%
  mutate(youden = tpr - fpr)

# find the optimal value
optimal_thresh &lt;- rates_log %&gt;%
  slice_max(youden)

# ROC curve
rates_log %&gt;%
  ggplot(aes(x = fpr, y = tpr, color = thresh)) +
  geom_path() +
  geom_point(data = optimal_thresh, color = &quot;red&quot;) +
  theme_bw()</code></pre>
<p><img src="https://www.dina-arch.com/collection/machine-learning-final-project/index_files/figure-html/unnamed-chunk-45-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>Logistic Regression:</p>
<pre class="r"><code>#Logistic Regression

# create prediction object
spam_predict &lt;- prediction(predictions = p_hat_glm, labels = test$candidate)

# compute error rates as a function of the probability threshold
perf_log &lt;- performance(prediction.obj = spam_predict, &#39;tpr&#39;, &#39;fpr&#39;)

# extract rates and threshold from perf_lda as a tibble
rates_log &lt;- tibble(fpr = perf_log@x.values,
                    tpr = perf_log@y.values,
                    thresh = perf_log@alpha.values) %&gt;%
  unnest(everything())

# compute youden&#39;s stat
rates_log &lt;- rates_log %&gt;%
  mutate(youden = tpr - fpr)

# find the optimal value
optimal_thresh &lt;- rates_log %&gt;%
  slice_max(youden)

# ROC curve
rates_log %&gt;%
  ggplot(aes(x = fpr, y = tpr, color = thresh)) +
  geom_path() +
  geom_point(data = optimal_thresh, color = &quot;red&quot;) +
  theme_bw()</code></pre>
<p><img src="https://www.dina-arch.com/collection/machine-learning-final-project/index_files/figure-html/unnamed-chunk-46-1.png" width="576" style="display: block; margin: auto;" /></p>
<p><strong>Both ROC curves look very different, with the logistic curve looking cleaner and has a higher optimal threshold. Both analyses have pros and cons and different classifiers are more appropriate for answering different kinds of questions about the election. Regarding decision trees, as we saw in the output, they are intuitive and easy to implement visualize and interpret. They also have the ability to be pruned by cost complexity. However, they are sensitive to small changes in the data, have high variance, and could fail if they separation in the feature space is hard to approximate. I think working with this scale of data is difficult to implement decision trees with because there is a lot of variability in data. Regarding logistic regression, they are interpretable, flexible, and can take in a large number of predictors. However, like decision trees, they can fail if data are separated in the feature space.</strong></p>
</div>
<div id="taking-it-further" class="section level1">
<h1>Taking it further</h1>
<ol start="21" style="list-style-type: decimal">
<li>This is an open question. Interpret and discuss any overall insights gained in this analysis and possible explanations. Use any tools at your disposal to make your case: visualize errors on the map, discuss what does or doesn’t seem reasonable based on your understanding of these methods, propose possible directions (for example, collecting additional data or domain knowledge). In addition, propose and tackle <em>at least</em> one more interesting question. Creative and thoughtful analyses will be rewarded!</li>
</ol>
<p><strong>As mentioned previously, both analyses have pros and cons and different classifiers are more appropriate for answering different kinds of questions about the election. In this example, it is shown that the logistic model performed better, providing a better misclassification error rate. I think the model would perform even better with theory-based predictors as that can influence the model, more predictors doesn’t necessarily mean better.</strong></p>
<ul>
<li>Instead of using the native attributes (the original features), we can use principal components to create new (and lower dimensional) sets of features with which to train a classification model. This sometimes improves classification performance. Compare classifiers trained on the original features with those trained on PCA features.</li>
</ul>
<p><strong>I like the idea of using PC components to reevaluate the classification methods used. The minimum number of PCs needed to capture 90% of the variance for county data is <em>13</em>, however, using 13 components makes interpretation tricky, as evaluating and labeling all 13 will be extremely time-consulting. To assess differences in bias-variance trade off between using PC and raw data, I will rerun both the decision tree analysis and the logistic regress using the first 4 principal components to predict the election results and compare.</strong></p>
<p>Rerun PCs with combined <code>county_winner</code> column for easier wrangling:</p>
<pre class="r"><code># Center and scale the data
county_winner_std &lt;- election_county %&gt;% 
  select(-candidate) %&gt;% 
  scale(center = T, scale = T)


# Compute SVD
x_svd &lt;- svd(county_winner_std)

# Get loadings
v_svd &lt;- x_svd$v

# compute principal components
county_winner_pc &lt;- county_winner_std %*% v_svd
colnames(county_winner_pc) &lt;- paste(&#39;PC&#39;, 1:26, sep = &#39;&#39;)

# scree and cumulative variance plots
pc_winner_vars &lt;- x_svd$d^2/(nrow(county_winner_std) - 1)

tibble(PC = 1:min(dim(county_winner_std)),
       Proportion = pc_winner_vars/sum(pc_winner_vars),
       Cumulative = cumsum(Proportion)) %&gt;%
  gather(key = &#39;measure&#39;, value = &#39;Variance Explained&#39;, 2:3) %&gt;%
  ggplot(aes(x = PC, y = `Variance Explained`)) +
  geom_point() +
  geom_path() +
  facet_wrap(~ measure) +
  theme_bw() </code></pre>
<p><img src="https://www.dina-arch.com/collection/machine-learning-final-project/index_files/figure-html/unnamed-chunk-47-1.png" width="576" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#tibble(PC = 1:min(dim(county_winner_std)),
#       Proportion = pc_winner_vars/sum(pc_winner_vars),
#       Cumulative = cumsum(Proportion)) %&gt;% 
#  head(15) %&gt;% 
#  pander()

v_svd[, 1:4] %&gt;%
  as.data.frame() %&gt;%
  mutate(variable = colnames(county_winner_std)) %&gt;%
  gather(key = &#39;PC&#39;, value = &#39;Loading&#39;, 1:4) %&gt;%
  arrange(variable) %&gt;%
  ggplot(aes(x = variable, y = Loading)) +
  geom_point(aes(shape = PC)) +
  theme_bw() +
  geom_hline(yintercept = 0, color = &#39;blue&#39;) +
  geom_path(aes(linetype = PC, group = PC)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = &#39;&#39;) +
  facet_wrap(~PC)</code></pre>
<p><img src="https://www.dina-arch.com/collection/machine-learning-final-project/index_files/figure-html/unnamed-chunk-47-2.png" width="576" style="display: block; margin: auto;" /></p>
<pre class="r"><code>county_pc_4 &lt;- county_winner_pc %&gt;% 
  as_tibble() %&gt;% 
  bind_cols(select(election_county, candidate)) %&gt;% 
  select(PC1:PC4, candidate)</code></pre>
<p>Note: Eigenvalues are slightly off because some observations were removed in the process of combining <code>county_winner</code> and <code>census_ct</code> but they are generally the same.</p>
<p><em>PC 1/Affluent</em>: High IncomePerCap, Employed, Income, and Professional. Low Child Poverty, Poverty, and Unemployment.</p>
<p><em>PC 2/Family Oriented</em>: High SelfEmployed, WorkAtHome, and FamilyWork. Low Women, PrivateWork, IncomeErr.</p>
<p><em>PC 3/Working Class in Suburb</em>: High White, Drive, Production, and Private Work. Low Minority, and Transit.</p>
<p><em>PC 4/Working Class in City</em>: High Carpool, Production, Employed. Low Citizen, Service, Office.</p>
<pre class="r"><code># hold out 20% of data as a test set
set.seed(12521)
county_part &lt;- resample_partition(county_pc_4, c(test = 0.2, train = 0.8))
train &lt;- as_tibble(county_part$train)
test &lt;- as_tibble(county_part$test)</code></pre>
<p>Decision Tree:</p>
<pre class="r"><code>#Train a decision tree - training partition
nmin &lt;- 5
tree_opts &lt;- tree.control(nobs = nrow(train), 
                          minsize = nmin, 
                          mindev = exp(-6))
t_small &lt;- tree(as.factor(candidate) ~ ., data = train,
                control = tree_opts, split = &#39;deviance&#39;) 
summary(t_small) </code></pre>
<pre><code>## 
## Classification tree:
## tree(formula = as.factor(candidate) ~ ., data = train, control = tree_opts, 
##     split = &quot;deviance&quot;)
## Number of terminal nodes:  56 
## Residual mean deviance:  0.3242 = 778.3 / 2401 
## Misclassification error rate: 0.0639 = 157 / 2457</code></pre>
<p>Tree before pruning:</p>
<pre class="r"><code>draw.tree(t_small, cex = 0.8, size = 2)</code></pre>
<p><img src="https://www.dina-arch.com/collection/machine-learning-final-project/index_files/figure-html/unnamed-chunk-50-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>Add cost-complexity pruning:</p>
<pre class="r"><code># cost-complexity pruning
nfolds &lt;- 10
cv_out &lt;- cv.tree(t_small, K = nfolds, method = &#39;deviance&#39;)

# convert to tibble
cv_df &lt;- tibble(alpha = cv_out$k,
                impurity = cv_out$dev,
                size = cv_out$size)

# choose optimal alpha
best_alpha &lt;- slice_min(cv_df, impurity) %&gt;%
  slice_min(size)

# select final tree
t_opt &lt;- prune.tree(t_small, k = best_alpha$alpha)
summary(t_opt) </code></pre>
<pre><code>## 
## Classification tree:
## snip.tree(tree = t_small, nodes = c(10L, 7L, 54L, 55L, 26L, 91L, 
## 23L, 25L, 90L, 9L))
## Number of terminal nodes:  13 
## Residual mean deviance:  0.4694 = 1147 / 2444 
## Misclassification error rate: 0.09565 = 235 / 2457</code></pre>
<p>Tree after pruning:</p>
<pre class="r"><code>draw.tree(t_opt, cex = 0.8, size = 5)</code></pre>
<p><img src="https://www.dina-arch.com/collection/machine-learning-final-project/index_files/figure-html/unnamed-chunk-52-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>Classification Errors on Test Partition - Before Pruning:</p>
<pre class="r"><code># predict on test data
preds_test_t0 &lt;- predict(t_small, newdata = county_part$test, type = &#39;class&#39;)
# examin misclassification errors on test set - First Tree
classes_test &lt;- as.data.frame(county_part$test) %&gt;% pull(candidate)
test_errors_t0 &lt;- table(class = classes_test, pred = preds_test_t0)
(test_errors_t0/rowSums(test_errors_t0)) </code></pre>
<pre><code>##                  pred
## class             Donald Trump Hillary Clinton
##   Donald Trump      0.95348837      0.04651163
##   Hillary Clinton   0.49484536      0.50515464</code></pre>
<p>Classification Errors on Test Partition - After Pruning:</p>
<pre class="r"><code># predict on test data
preds_test_t0 &lt;- predict(t_opt, newdata = county_part$test, type = &#39;class&#39;)
# Pruned - Tree Error
classes_test &lt;- as.data.frame(county_part$test) %&gt;% pull(candidate)
test_errors_t0 &lt;- table(class = classes_test, pred = preds_test_t0)
(test_errors_t0/rowSums(test_errors_t0)) </code></pre>
<pre><code>##                  pred
## class             Donald Trump Hillary Clinton
##   Donald Trump      0.93410853      0.06589147
##   Hillary Clinton   0.51546392      0.48453608</code></pre>
<p><strong>After training a decision tree before pruning, the resulting classification tree had 56 terminal nodes and a misclassification error rate of 0.0639. The four PCs were used. Already, we see that the misclassifciation error is much higher than using the full dataset shown earlier. After pruning the classification tree, now there are 13 terminal nodes and a misclassifcation error rate of 0.09565. Compared to the full dataset the pruned decision tree had less terminal nodes (5), but the misclassification error rate was slightly similar (0.08). The interpretation is slightly different now that we have to identify the PC on the tree. For example, if the loading on PC3 is less than -.610 (or in this case less affluent counties) and the loading on PC2 is less than -1.47912 (or in this case less family oriented counties), and the loading on PC3 is less than -3.40997 (even less affleunt counties) then it is likely they voted for Hillary Clinton. Already, this interpretation is extremely confusing compared to using all predictors.</strong></p>
<p>Logistic Regression:</p>
<pre class="r"><code>fit_glm &lt;- glm(as.factor(candidate) ~ ., family = &#39;binomial&#39;, data=train)

summary(fit_glm) </code></pre>
<pre><code>## 
## Call:
## glm(formula = as.factor(candidate) ~ ., family = &quot;binomial&quot;, 
##     data = train)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.1258  -0.4289  -0.2081  -0.1065   3.3147  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -2.76655    0.11026 -25.091  &lt; 2e-16 ***
## PC1         -0.05276    0.02655  -1.987   0.0469 *  
## PC2         -0.64696    0.04784 -13.523  &lt; 2e-16 ***
## PC3         -0.86938    0.05006 -17.368  &lt; 2e-16 ***
## PC4         -0.39303    0.06011  -6.538 6.23e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 2071.8  on 2456  degrees of freedom
## Residual deviance: 1262.3  on 2452  degrees of freedom
## AIC: 1272.3
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<p><strong>All four PCs are significant predictors of candidate. And it looks like all for PCs have similar interpretation: the probability of a county voting for Donald Trump decreases for each PC estimate. This was not the case when all variables were entered in the logistic model.</strong></p>
<p>Errors (Test Partition):</p>
<pre class="r"><code># compute estimated probabilities
p_hat_glm &lt;- predict(fit_glm, test, type = &#39;response&#39;)

# bayes classifier
y_hat_glm &lt;- factor(p_hat_glm &gt; 0.5, labels = c(&#39;No&#39;, &#39;Yes&#39;))

# errors
error_glm &lt;- table(test$candidate, y_hat_glm)
(error_glm / rowSums(error_glm))</code></pre>
<pre><code>##                  y_hat_glm
##                           No        Yes
##   Donald Trump    0.95155039 0.04844961
##   Hillary Clinton 0.52577320 0.47422680</code></pre>
<p><strong>The true positve for Hillary Clinton in the model is a lot less than the model with all variables, however.</strong></p>
<p>ROC Curves:</p>
<p>Decision Tree:</p>
<pre class="r"><code>#Decision Tree
t_predict &lt;- predict(t_small, newdata = test) %&gt;% 
  as_tibble()

tree_predict &lt;- prediction(t_predict[,2], labels = test$candidate)

# compute error rates as a function of the probability threshold
perf_log &lt;- performance(prediction.obj = tree_predict, &#39;tpr&#39;, &#39;fpr&#39;)

# extract rates and threshold from perf_lda as a tibble
rates_log &lt;- tibble(fpr = perf_log@x.values,
                    tpr = perf_log@y.values,
                    thresh = perf_log@alpha.values) %&gt;%
  unnest(everything())

# compute youden&#39;s stat
rates_log &lt;- rates_log %&gt;%
  mutate(youden = tpr - fpr)

# find the optimal value
optimal_thresh &lt;- rates_log %&gt;%
  slice_max(youden)

# ROC curve
rates_log %&gt;%
  ggplot(aes(x = fpr, y = tpr, color = thresh)) +
  geom_path() +
  geom_point(data = optimal_thresh, color = &quot;red&quot;) +
  theme_bw()</code></pre>
<p><img src="https://www.dina-arch.com/collection/machine-learning-final-project/index_files/figure-html/unnamed-chunk-57-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>Logistic Regression:</p>
<pre class="r"><code>#Logistic Regression

# create prediction object
spam_predict &lt;- prediction(predictions = p_hat_glm, labels = test$candidate)

# compute error rates as a function of the probability threshold
perf_log &lt;- performance(prediction.obj = spam_predict, &#39;tpr&#39;, &#39;fpr&#39;)

# extract rates and threshold from perf_lda as a tibble
rates_log &lt;- tibble(fpr = perf_log@x.values,
                    tpr = perf_log@y.values,
                    thresh = perf_log@alpha.values) %&gt;%
  unnest(everything())

# compute youden&#39;s stat
rates_log &lt;- rates_log %&gt;%
  mutate(youden = tpr - fpr)

# find the optimal value
optimal_thresh &lt;- rates_log %&gt;%
  slice_max(youden)

# ROC curve
rates_log %&gt;%
  ggplot(aes(x = fpr, y = tpr, color = thresh)) +
  geom_path() +
  geom_point(data = optimal_thresh, color = &quot;red&quot;) +
  theme_bw()</code></pre>
<p><img src="https://www.dina-arch.com/collection/machine-learning-final-project/index_files/figure-html/unnamed-chunk-58-1.png" width="576" style="display: block; margin: auto;" /></p>
<p><strong>Overall, it seems like using the first four principal components did not improve neither the decision tree or logistic regression model. This could be due to many factors but the main one I can think of is that the first four PCs only capture 59% of the variance in the variables. The decision tree did not make sense to use even if it had a better misclassification rate as the interpretability of the tree did not as much sense as the model with all variables. While the logistic model did have all significant predictors, the error rate was much higher than the model with all variables, but less predictors were used. In the future, I would select variables based on theory, use PCA to reduce the dimensions and capture more variance than I did now, and then re-run the model.</strong></p>
</div>

      </section>
      <footer class="post-footer">
        <div class="post-pagination dt w-100 mt4 mb2">
  
  
  
  
</div>

      </footer>
    </article>
    
  </section>
</main>

<aside class="page-sidebar" role="complementary">
                         
 











  <img src="/collection/featured-sidebar.jpg" class="db ma0">

                         
 



<div class="flex items-start sticky ph4 pb4 flex-row">
  <div class="w-two-thirds w-50-l ph0">
    <h2 class="mv3 f5 fw7 ttu tracked">
      <a class="no-underline dim" href="/collection/">Outline</a></h2>
    <nav id="SectionTableOfContents" aria-label="SectionTableOfContents">
        <ul>
        
          
          
          
          <details  class="">
            <summary class="" hugo-nav="/collection/linear-models/"><a href="https://www.dina-arch.com/collection/linear-models/">Linear Models for Data Analysis</a></summary>
            
              
              <li class="" hugo-nav="/collection/linear-models/01-data-cleaning/"><a href="https://www.dina-arch.com/collection/linear-models/01-data-cleaning/">Lab 1: Data Screening and Cleaning</a></li>
            
              
              <li class="" hugo-nav="/collection/linear-models/02-slr/"><a href="https://www.dina-arch.com/collection/linear-models/02-slr/">Lab 2: Simple Linear Regression</a></li>
            
              
              <li class="" hugo-nav="/collection/linear-models/03-moderation/"><a href="https://www.dina-arch.com/collection/linear-models/03-moderation/">Lab 3: Moderation</a></li>
            
              
              <li class="" hugo-nav="/collection/linear-models/04-mediation/"><a href="https://www.dina-arch.com/collection/linear-models/04-mediation/">Lab 4: Mediation</a></li>
            
          </details>
          
          </li>
        
          
          
          
          <details  class="">
            <summary class="" hugo-nav="/collection/day02/"><a href="https://www.dina-arch.com/collection/day02/">Day 02</a></summary>
            
              
              <li class="" hugo-nav="/collection/day02/01-netlify/"><a href="https://www.dina-arch.com/collection/day02/01-netlify/">Netlify</a></li>
            
              
              <li class="" hugo-nav="/collection/day02/02-blogdown/"><a href="https://www.dina-arch.com/collection/day02/02-blogdown/">Using blogdown</a></li>
            
              
              <li class="" hugo-nav="/collection/day02/03-blogdown/"><a href="https://www.dina-arch.com/collection/day02/03-blogdown/">Warm woolen mittens</a></li>
            
          </details>
          
          </li>
        
          
          
          <li class="active" hugo-nav="/collection/machine-learning-final-project/">
            <a href="https://www.dina-arch.com/collection/machine-learning-final-project/">Machine Learning - Final Project</a></li>
          
          </li>
        
        </ul>
    </nav>
  </div>
  <details id="PageTableOfContents">
    <summary><h2 class="mv0 f5 fw7 ttu tracked dib">On this page<h2></summary>
    <div class="pl2 pr0 mh0">
    
    </div>
  </details>
  
</div>

</aside>

<footer class="site-footer pv4 bt b--transparent ph5" role="contentinfo">
  <nav class="db dt-l w-100">
    <p class="site-copyright f7 db dtc-l v-mid w-100 w-33-l tc tl-l pv2 pv0-l mv0 lh-copy">
      &copy; 2022 Dina Arch
      <span class="middot-divider"></span>
      Made with <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title"><a xmlns:dct="http://purl.org/dc/terms/" href="https://github.com/hugo-apero/" rel="dct:source">Hugo Apéro</a></span>.
      <br />
      
Based on <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title"><a xmlns:dct="http://purl.org/dc/terms/" href="https://github.com/formspree/blogophonic-hugo" rel="dct:source">Blogophonic</a></span> by <a xmlns:cc="http://creativecommons.org/ns#" href="https://formspree.io" property="cc:attributionName" rel="cc:attributionURL">Formspree</a>.
    </p>
    
    <div class="site-social-links db dtc-l v-mid w-100 w-33-l tc pv2 pv0-l mv0">
      <div class="social-icon-links" aria-hidden="true">
  
  
    
    
    
      
    
    
    
    
    
    <a class="link dib h1 w1 ml0 mr2 f6 o-90 glow" href="mailto:dnaji@ucsb.edu" title="envelope" >
      <i class="fas fa-envelope fa-lg fa-fw"></i>
    </a>
  
    
    
    
      
    
    
    
    
    
      
    
    <a class="link dib h1 w1 ml0 mr2 f6 o-90 glow" href="https://github.com/dinanajiarch" title="github" target="_blank" rel="noopener">
      <i class="fab fa-github fa-lg fa-fw"></i>
    </a>
  
    
    
    
      
    
    
    
    
    
      
    
    <a class="link dib h1 w1 ml0 mr2 f6 o-90 glow" href="https://twitter.com/dnajiarch" title="twitter" target="_blank" rel="noopener">
      <i class="fab fa-twitter fa-lg fa-fw"></i>
    </a>
  
    
    
    
      
    
    
    
    
    
      
    
    <a class="link dib h1 w1 ml0 mr2 f6 o-90 glow" href="https://www.linkedin.com/in/dina-naji-arch-22649396/" title="linkedin" target="_blank" rel="noopener">
      <i class="fab fa-linkedin fa-lg fa-fw"></i>
    </a>
  
    
    
    
    
    
    
    
      
    
    <a class="link dib h1 w1 ml0 mr2 f6 o-90 glow" href="https://orcid.org/0000-0002-2716-0798" title="orcid" target="_blank" rel="noopener">
      <i class="ai ai-orcid fa-lg fa-fw"></i>
    </a>
  
</div>

    </div>
    
    <div class="site-links f6 db dtc-l v-mid w-100 w-67-l tc tr-l pv2 pv0-l mv0">
      
    </div>
  </nav>
  
    <script>

    var i, text, code, codes = document.getElementsByTagName('code');
    for (let i = 0; i < codes.length;) {
      code = codes[i];
      if (code.parentNode.tagName !== 'PRE' && code.childElementCount === 0) {
        text = code.textContent;
        if (/^\$[^$]/.test(text) && /[^$]\$$/.test(text)) {
          text = text.replace(/^\$/, '\\(').replace(/\$$/, '\\)');
          code.textContent = text;
        }
        if (/^\\\((.|\s)+\\\)$/.test(text) ||
            /^\\\[(.|\s)+\\\]$/.test(text) ||
            /^\$(.|\s)+\$$/.test(text) ||
            /^\\begin\{([^}]+)\}(.|\s)+\\end\{[^}]+\}$/.test(text)) {
          code.outerHTML = code.innerHTML;  
          continue;
        }
      }
      i++;
    }
</script>

  
    
    
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.13.13/dist/katex.min.css" integrity="sha384-RZU/ijkSsFbcmivfdRBQDtwuwVqK7GMOw6IMvKyeWL2K5UAlyp6WonmB8m7Jd0Hn" crossorigin="anonymous">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.13/dist/katex.min.js" integrity="sha384-pK1WpvzWVBQiP0/GjnvRxV4mOb0oxFuyRxJlk6vVw146n3egcN5C925NCP7a7BY8" crossorigin="anonymous"></script>
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.13/dist/contrib/auto-render.min.js" integrity="sha384-vZTG03m+2yp6N6BNi5iM4rW4oIwk5DfcNdFfxkk9ZWpDriOkXX8voJBFrAO7MpVl" crossorigin="anonymous" onload="renderMathInElement(document.body);"></script>



    
  
  
</footer>

      </div>
    </body>
</html>
